services:
  - type: web
    name: django-ecommerce
    env: python
    rootDirectory: .
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn projectname.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: projectname.settings
